### ISSUE TITLE
Dengue Stop Milestones for GSoC 2020

### ISSUE THREAD

**Issue by DonOmalVindula** [scorelab/DengueStop#4]
Please find the detailed project plan [here.](https://docs.google.com/document/d/1Yhu3SrcbS6-3lBwCDFJQ2sGnQfRRdk_eN8BZ1VZ5vXM/edit?usp=sharing)

<details><summary>Proposed UI Mockups</summary>

### Login Screen (Mobile)
<kbd>![Login](https://user-images.githubusercontent.com/42619922/84315881-e3436180-ab87-11ea-82d2-a5d5167c535a.png)</kbd>

### Signup Screen (Mobile)
<kbd>![Register](https://user-images.githubusercontent.com/42619922/84315915-ecccc980-ab87-11ea-924a-17b558e921a7.png)</kbd>

### Home Screen (Mobile)
<kbd>![Home](https://user-images.githubusercontent.com/42619922/84315923-f0605080-ab87-11ea-9074-db8c3fe09db8.png)</kbd>

### New Incident Screen (Mobile)
<kbd>![Report Incident](https://user-images.githubusercontent.com/42619922/84315941-f6eec800-ab87-11ea-9f86-b3560614e07a.png)</kbd>

### My Reports Screen (Mobile)
<kbd>![My Reports](https://user-images.githubusercontent.com/42619922/84315948-f9e9b880-ab87-11ea-85d4-9657a2306955.png)</kbd>

### My Profile Screen (Mobile)
<kbd>![My Profile](https://user-images.githubusercontent.com/42619922/84316133-3ae1cd00-ab88-11ea-946a-ca326762bef5.png)</kbd>

### Login Screen (Web)
<kbd>![Login_wo_logo](https://user-images.githubusercontent.com/42619922/84315853-d9216300-ab87-11ea-8d90-a7a8bc9cbbe2.png)</kbd>

### Dashboard Screen (Web)
<kbd>![Heat Map](https://user-images.githubusercontent.com/42619922/84316167-47febc00-ab88-11ea-8f3a-6235c18cd147.png)</kbd>

### Metrics Screen (Web)
<kbd>![Metrics](https://user-images.githubusercontent.com/42619922/84316177-4d5c0680-ab88-11ea-942a-8dd05c07db0f.png)</kbd>

### Patient/Incident List Screen (Web)
<kbd>![Patient List](https://user-images.githubusercontent.com/42619922/84316185-52b95100-ab88-11ea-974a-a5bdfb73aaf9.png)</kbd>

### Events Screen (Web)
<kbd>![Event List](https://user-images.githubusercontent.com/42619922/84316203-5c42b900-ab88-11ea-9a1d-b4a0eca7aee0.png)</kbd>

### Create Event Screen (Web)
<kbd>![Event List – Create New](https://user-images.githubusercontent.com/42619922/84316213-606ed680-ab88-11ea-9c97-742555cb5156.png)</kbd>

</details>

### Milestone 1

- [x] Setting up the new project and initial configurations. (Mobile App)

- [x] Designing the database structure.

- [x] Creating the database and the server using Flask.

- [x] Setting up end-points to be consumed by the mobile application.

- [x] Incident reporting and viewing feature. (Mobile App)

- [x] User registration and authentication. (Mobile App)

- [x] User profile viewing and editing feature. (Mobile App)

- [x] Implementing events feature - front-end (Mobile App)

- [x] Setting up the new project and initial configurations. (Web App)

- [x] Testing for milestone 1.

- [x] Documentation for milestone 1.

### Milestone 2

- [x] Code refactor after milestone 1.

- [x] Dashboard Component - Heatmap (Web App)

- [x] Dashboard Component - Incident receiving feature (Web App)

- [x] Dashboard Component - Incident verification feature (Web App)

- [x] Dashboard Component - Incident summary feature (Web App)

- [x] Patient/Incident List Component - Incident view feature (Web App)

- [x] Patient/Incident List Component - Incident searching feature (Web App)

- [x] Patient/Incident List Component - Incident filtering/sorting feature(Web App)

- [x] Metrics Component - Chart visualization (Web App)

- [x] Metrics Component - Metrics logic (Web App)

- [x] Testing for milestone 2.

- [x] Documentation for milestone 2.

### Milestone 3

- [x] Code refactor after milestone 2.

- [x] User registration and authentication. (Web App)

- [x] Alerts/Events sending feature. (Web App)

- [x] Implementing events feature - back-end (Mobile App)

- [x] Testing for milestone 3.

- [x] Documentation for milestone 3.

- [x] Finalizing the project.

**Comment by ivantha** [comment]
Thanks @DonOmalVindula for your valuable contribution to DengueStop during GSoC 2020.

**Comment by DonOmalVindula** [comment]
> Thanks @DonOmalVindula for your valuable contribution to DengueStop during GSoC 2020.

You're very welcome @ivantha!
